In [29]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix, precision_score

In [30]:
df=pd.read_csv("Social_media_impact_on_life.csv")

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1705 entries, 0 to 1704
Data columns (total 11 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Student_ID                    1705 non-null   int64
 1   Age                           1705 non-null   int64
 2   Gender                        1705 non-null   object
 3   Academic_Level                1705 non-null   object
 4   Country                       1705 non-null   object
 5   Avg_Daily_Usage_Hours         1705 non-null   float64
 6   Most_Used_Platform            1705 non-null   object
 7   Affects_Academic_Performance  1705 non-null   object
 8   Sleep_Hours_Per_Night         1705 non-null   float64
 9   Mental_Health_Score           1705 non-null   float64
 10  Overall_Impact                1705 non-null   object
dtypes: float64(3), int64(2), object(6)
memory usage: 146.7+ KB

In [32]:
df.head()

,Student_ID,Age,Gender,Academic_Level,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Affects_Academic_Performance,Sleep_Hours_Per_Night,Mental_Health_Score,Overall_Impact
0,232,21,Male,Undergraduate,Other,4.0,Facebook,No,6.7,6.8,Neutral
1,564,23,Female,Undergraduate,Other,1.6,LinkedIn,No,8.6,7.6,Positive
2,788,22,Male,Graduate,Canada,4.6,Instagram,No,6.7,7.0,Neutral
3,686,18,Male,Undergraduate,Other,7.0,Snapchat,Yes,5.4,5.3,Negative
4,608,24,Female,High School,Other,7.5,Facebook,Yes,5.0,4.4,Negative

Kolone Student_ID, Affects_Academic_Performance i Overall_Imapct su izbačene iz dataset-a.
Kolona **Student_ID** nije relevantna za bilo kakav oblik razmatranja prilikom analize, a kasnije i treniranja podataka, dok kolone **Affects_Academic_Performance** i **Overall_Imapct** se odnose na one kolone na osnovu kojih bi trebali dobiti rezultate treniranja.

In [33]:
df.drop(columns=['Student_ID', 'Affects_Academic_Performance', 'Overall_Impact'], inplace=True)

Prikazani su svi nazivi kolona koje nisu numeričke:

In [34]:
categorical_col = df.select_dtypes("object").columns
categorical_col

Index(['Gender', 'Academic_Level', 'Country', 'Most_Used_Platform'], dtype='object')

Na osnovu kolona koje nisu numeričke je kreiran zaseban dataframe:

In [35]:
df_categoric = df[categorical_col]

Prikaz prvih 10 kolona novog dataframe-a:

In [36]:
df_categoric.head(10)

   Gender Academic_Level Country Most_Used_Platform
0    Male  Undergraduate   Other           Facebook
1  Female  Undergraduate   Other           LinkedIn
2    Male       Graduate  Canada          Instagram
3    Male  Undergraduate   Other           Snapchat
4  Female    High School   Other           Facebook
5  Female    High School   Other            Twitter
6  Female       Graduate   Other          Instagram
7  Female       Graduate   Other           Facebook
8    Male  Undergraduate     USA            YouTube
9    Male    High School   Other             TikTok

U nastavku su kolone koje nisu numeričke konvertovane u numeričke varijable:

In [37]:
encoder = LabelEncoder()

In [38]:
df['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [39]:
df_categoric['Gender'] = encoder.fit_transform(df_categoric['Gender'])
df['Gender'] = encoder.fit_transform(df['Gender'])

/tmp/ipykernel_419/3519347496.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_categoric['Gender'] = encoder.fit_transform(df_categoric['Gender'])

In [40]:
df['Academic_Level'].unique()

array(['Undergraduate', 'Graduate', 'High School'], dtype=object)

In [41]:
df_categoric['Academic_Level']= df_categoric['Academic_Level'].map({'High School':0, 'Undergraduate':1, 'Graduate':2})
df['Academic_Level'] = df['Academic_Level'].map({'High School':0, 'Undergraduate':1, 'Graduate':2})

/tmp/ipykernel_419/1233225046.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_categoric['Academic_Level']= df_categoric['Academic_Level'].map({'High School':0, 'Undergraduate':1, 'Graduate':2})

In [42]:
df['Country'].unique()

array(['Other', 'Canada', 'USA', 'India', 'Australia', 'UK', 'Germany',
       'Bangladesh', 'Brazil', 'Japan', 'South Korea', 'France', 'Spain',
       'Italy', 'Mexico', 'Russia', 'China', 'Sweden', 'Norway',
       'Denmark', 'Netherlands', 'Belgium', 'Switzerland', 'Austria',
       'Portugal', 'Greece', 'Ireland', 'New Zealand', 'Singapore',
       'Malaysia', 'Thailand', 'Vietnam', 'Philippines', 'Indonesia',
       'Taiwan', 'Hong Kong', 'Turkey', 'Israel', 'UAE', 'Egypt',
       'Morocco', 'South Africa', 'Nigeria', 'Kenya', 'Ghana',
       'Argentina', 'Chile', 'Colombia', 'Peru', 'Venezuela', 'Ecuador',
       'Uruguay', 'Paraguay', 'Bolivia', 'Costa Rica', 'Panama',
       'Jamaica', 'Trinidad', 'Bahamas', 'Iceland', 'Finland', 'Poland',
       'Romania', 'Hungary', 'Czech Republic', 'Slovakia', 'Croatia',
       'Serbia', 'Slovenia', 'Bulgaria', 'Estonia', 'Latvia', 'Lithuania',
       'Ukraine', 'Moldova', 'Belarus', 'Kazakhstan', 'Uzbekistan',
       'Kyrgyzstan', 'Tajikistan', 'Armenia', 'Georgia', 'Azerbaijan',
       'Cyprus', 'Malta', 'Luxembourg', 'Monaco', 'Andorra', 'San Marino',
       'Vatican City', 'Liechtenstein', 'Montenegro', 'Albania',
       'North Macedonia', 'Kosovo', 'Bosnia', 'Qatar', 'Kuwait',
       'Bahrain', 'Oman', 'Jordan', 'Lebanon', 'Iraq', 'Yemen', 'Syria',
       'Afghanistan', 'Pakistan', 'Nepal', 'Bhutan', 'Sri Lanka',
       'Maldives'], dtype=object)

In [43]:
df_categoric['Country'] = encoder.fit_transform(df_categoric['Country'])
df['Country'] = encoder.fit_transform(df['Country'])

/tmp/ipykernel_419/179382923.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_categoric['Country'] = encoder.fit_transform(df_categoric['Country'])

In [44]:
df.head()

,Age,Gender,Academic_Level,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Sleep_Hours_Per_Night,Mental_Health_Score
0,21,1,1,73,4.0,Facebook,6.7,6.8
1,23,0,1,73,1.6,LinkedIn,8.6,7.6
2,22,1,2,18,4.6,Instagram,6.7,7.0
3,18,1,1,73,7.0,Snapchat,5.4,5.3
4,24,0,0,73,7.5,Facebook,5.0,4.4

In [18]:
df['Most_Used_Platform'].unique()

array(['Facebook', 'LinkedIn', 'Instagram', 'Snapchat', 'Twitter',
       'YouTube', 'TikTok', 'LINE', 'KakaoTalk', 'VKontakte', 'WhatsApp',
       'WeChat'], dtype=object)

In [45]:
df_categoric['Most_Used_Platform'] = encoder.fit_transform(df_categoric['Most_Used_Platform'])
df['Most_Used_Platform'] = encoder.fit_transform(df['Most_Used_Platform'])

/tmp/ipykernel_419/416981615.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_categoric['Most_Used_Platform'] = encoder.fit_transform(df_categoric['Most_Used_Platform'])

In [46]:
df.head()

,Age,Gender,Academic_Level,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Sleep_Hours_Per_Night,Mental_Health_Score
0,21,1,1,73,4.0,0,6.7,6.8
1,23,0,1,73,1.6,4,8.6,7.6
2,22,1,2,18,4.6,1,6.7,7.0
3,18,1,1,73,7.0,5,5.4,5.3
4,24,0,0,73,7.5,0,5.0,4.4