In [7]:
import pandas as pd

In [11]:
df1=pd.read_csv("1_airline_passenger_satisfaction.csv")

In [12]:
df1.head()

,ID,Gender,Age,Customer Type,Type of Travel,Class,Flight Distance,Departure Delay,Arrival Delay,Departure and Arrival Time Convenience,...,On-board Service,Seat Comfort,Leg Room Service,Cleanliness,Food and Drink,In-flight Service,In-flight Wifi Service,In-flight Entertainment,Baggage Handling,Satisfaction
0,1,Male,48,First-time,Business,Business,821.0,2.0,5.0,3.0,...,3.0,5.0,2.0,5.0,5.0,5.0,3.0,5.0,5.0,Neutral or Dissatisfied
1,2,Female,35,Returning,Business,Business,821.0,26.0,39.0,2.0,...,5.0,4.0,5.0,5.0,3.0,5.0,2.0,5.0,5.0,Satisfied
2,3,Male,41,Returning,Business,Business,853.0,0.0,0.0,4.0,...,3.0,5.0,3.0,5.0,5.0,3.0,4.0,3.0,3.0,Satisfied
3,4,Male,50,Returning,Business,Business,1905.0,0.0,0.0,2.0,...,5.0,5.0,5.0,4.0,4.0,5.0,2.0,5.0,5.0,Satisfied
4,5,Female,49,Returning,Business,Business,3470.0,0.0,1.0,3.0,...,3.0,4.0,4.0,5.0,4.0,3.0,3.0,3.0,3.0,Satisfied

In [13]:
df1.dtypes

ID                                          int64
Gender                                     object
Age                                         int64
Customer Type                              object
Type of Travel                             object
Class                                      object
Flight Distance                           float64
Departure Delay                           float64
Arrival Delay                             float64
Departure and Arrival Time Convenience    float64
Ease of Online Booking                    float64
Check-in Service                          float64
Online Boarding                           float64
Gate Location                             float64
On-board Service                          float64
Seat Comfort                              float64
Leg Room Service                          float64
Cleanliness                               float64
Food and Drink                            float64
In-flight Service                         float64
In-flight Wifi Service                    float64
In-flight Entertainment                   float64
Baggage Handling                          float64
Satisfaction                               object
dtype: object

In [14]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42448 entries, 0 to 42447
Data columns (total 24 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   ID                                      42448 non-null  int64
 1   Gender                                  42448 non-null  object
 2   Age                                     42448 non-null  int64
 3   Customer Type                           42447 non-null  object
 4   Type of Travel                          42447 non-null  object
 5   Class                                   42447 non-null  object
 6   Flight Distance                         42447 non-null  float64
 7   Departure Delay                         42447 non-null  float64
 8   Arrival Delay                           42283 non-null  float64
 9   Departure and Arrival Time Convenience  42447 non-null  float64
 10  Ease of Online Booking                  42447 non-null  float64
 11  Check-in Service                        42447 non-null  float64
 12  Online Boarding                         42447 non-null  float64
 13  Gate Location                           42447 non-null  float64
 14  On-board Service                        42447 non-null  float64
 15  Seat Comfort                            42447 non-null  float64
 16  Leg Room Service                        42447 non-null  float64
 17  Cleanliness                             42447 non-null  float64
 18  Food and Drink                          42447 non-null  float64
 19  In-flight Service                       42447 non-null  float64
 20  In-flight Wifi Service                  42447 non-null  float64
 21  In-flight Entertainment                 42447 non-null  float64
 22  Baggage Handling                        42447 non-null  float64
 23  Satisfaction                            42447 non-null  object
dtypes: float64(17), int64(2), object(5)
memory usage: 7.8+ MB

In [15]:
df1.describe()

,ID,Age,Flight Distance,Departure Delay,Arrival Delay,Departure and Arrival Time Convenience,Ease of Online Booking,Check-in Service,Online Boarding,Gate Location,On-board Service,Seat Comfort,Leg Room Service,Cleanliness,Food and Drink,In-flight Service,In-flight Wifi Service,In-flight Entertainment,Baggage Handling
count,42448.00000,42448.000000,42447.000000,42447.000000,42283.000000,42447.000000,42447.000000,42447.000000,42447.000000,42447.000000,42447.000000,42447.000000,42447.000000,42447.000000,42447.000000,42447.000000,42447.000000,42447.000000,42447.000000
mean,21224.50000,38.873516,1049.194077,15.638726,16.931485,3.064669,2.731901,3.164228,3.151295,2.980234,3.278017,3.348058,3.265296,3.240158,3.205645,3.507763,2.769407,3.351167,3.511862
std,12253.82645,15.098538,995.438988,40.921227,41.803139,1.536957,1.413739,1.312485,1.366155,1.280063,1.325239,1.329230,1.346432,1.336407,1.346716,1.229393,1.345815,1.339151,1.228344
min,1.00000,2.000000,31.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,10612.75000,27.000000,351.000000,0.000000,0.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,3.000000,2.000000,2.000000,3.000000
50%,21224.50000,39.000000,657.000000,0.000000,0.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,4.000000,3.000000,3.000000,3.000000,4.000000,3.000000,4.000000,4.000000
75%,31836.25000,50.000000,1290.000000,11.000000,14.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000
max,42448.00000,85.000000,4983.000000,1017.000000,1011.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000

In [ ]:
df1["Gender"].value_counts()

Gender
Female    63448
Male      61552
Name: count, dtype: int64

In [ ]:
df1["Customer Type"].value_counts()

Customer Type
Returning     102150
First-time     22850
Name: count, dtype: int64

In [ ]:
df1["Type of Travel"].value_counts()

Type of Travel
Business    86340
Personal    38660
Name: count, dtype: int64

In [ ]:
df1["Class"].value_counts()

Class
Business        59496
Economy         56343
Economy Plus     9161
Name: count, dtype: int64

In [ ]:
df1["Satisfaction"].value_counts()

Satisfaction
Neutral or Dissatisfied    70752
Satisfied                  54248
Name: count, dtype: int64

In [ ]:
df1["Gender"].value_counts(normalize=True) * 100

Gender
Female    50.7584
Male      49.2416
Name: proportion, dtype: float64

In [ ]:
df1["Customer Type"].value_counts(normalize=True) * 100

Customer Type
Returning     81.72
First-time    18.28
Name: proportion, dtype: float64

In [ ]:
df1["Type of Travel"].value_counts(normalize=True) * 100

Type of Travel
Business    69.072
Personal    30.928
Name: proportion, dtype: float64

In [ ]:
df1["Class"].value_counts(normalize=True) * 100

Class
Business        47.5968
Economy         45.0744
Economy Plus     7.3288
Name: proportion, dtype: float64

In [ ]:
df1["Satisfaction"].value_counts(normalize=True) * 100

Satisfaction
Neutral or Dissatisfied    56.6016
Satisfied                  43.3984
Name: proportion, dtype: float64

In [ ]:

# aritmetička sredina
mean = df1["Age"].mean()

# medijan
median = df1["Age"].median()

# moda
mode = df1["Age"].mode()

# minimum
min_val = df1["Age"].min()

# maksimum
max_val = df1["Age"].max()

print(mean, median, mode, min_val, max_val)

39.420872 40.0 0    39
Name: Age, dtype: int64 7 85

In [ ]:
# aritmetička sredina
mean = df1["Flight Distance"].mean()

# medijan
median = df1["Flight Distance"].median()

# moda
mode = df1["Flight Distance"].mode()

# minimum
min_val = df1["Flight Distance"].min()

# maksimum
max_val = df1["Flight Distance"].max()

print(mean, median, mode, min_val, max_val)

1180.574136 834.0 0    337
Name: Flight Distance, dtype: int64 31 4983

In [ ]:
# aritmetička sredina
mean = df1["Departure Delay"].mean()

# medijan
median = df1["Departure Delay"].median()

# moda
mode = df1["Departure Delay"].mode()

# minimum
min_val = df1["Departure Delay"].min()

# maksimum
max_val = df1["Departure Delay"].max()

print(mean, median, mode, min_val, max_val)

14.93268 0.0 0    0
Name: Departure Delay, dtype: int64 0 1592

In [ ]:
# aritmetička sredina
mean = df1["Arrival Delay"].mean()

# medijan
median = df1["Arrival Delay"].median()

# moda
mode = df1["Arrival Delay"].mode()

# minimum
min_val = df1["Arrival Delay"].min()

# maksimum
max_val = df1["Arrival Delay"].max()

print(mean, median, mode, min_val, max_val)

15.289173834895365 0.0 0    0.0
Name: Arrival Delay, dtype: float64 0.0 1584.0

In [ ]:
df1["Departure and Arrival Time Convenience"].value_counts()

Departure and Arrival Time Convenience
4    30679
5    27036
3    21534
2    20668
1    18662
0     6421
Name: count, dtype: int64

In [ ]:
df1["Departure and Arrival Time Convenience"].mean()

np.float64(3.059968)

In [ ]:
bez_nula = df1["Departure and Arrival Time Convenience"][df1["Departure and Arrival Time Convenience"] != 0]

mean_bez_nula = bez_nula.mean()
print(f"Aritmetička sredina bez nula: {mean_bez_nula:.2f}")

Aritmetička sredina bez nula: 3.23

In [ ]:
df1["Ease of Online Booking"].value_counts()

Ease of Online Booking
3    29197
2    28930
4    23510
1    21055
5    16789
0     5519
Name: count, dtype: int64

In [ ]:
df1["Ease of Online Booking"].mean()

np.float64(2.755928)

In [ ]:
bez_nula = df1["Ease of Online Booking"][df1["Ease of Online Booking"] != 0]

mean_bez_nula = bez_nula.mean()
print(f"Aritmetička sredina bez nula: {mean_bez_nula:.2f}")

Aritmetička sredina bez nula: 2.88

In [ ]:
df1["Check-in Service"].value_counts()

Check-in Service
4    34883
3    34038
5    24895
2    15607
1    15576
0        1
Name: count, dtype: int64

In [ ]:
df1["Check-in Service"].mean()

np.float64(3.303288)

In [ ]:
bez_nula = df1["Check-in Service"][df1["Check-in Service"] != 0]

mean_bez_nula = bez_nula.mean()
print(f"Aritmetička sredina bez nula: {mean_bez_nula:.2f}")

Aritmetička sredina bez nula: 3.30

In [ ]:
df1["Online Boarding"].value_counts()

Online Boarding
4    37041
3    26085
5    24944
2    21145
1    12787
0     2998
Name: count, dtype: int64

In [ ]:
df1["Online Boarding"].mean()

np.float64(3.249728)

In [ ]:
bez_nula = df1["Online Boarding"][df1["Online Boarding"] != 0]

mean_bez_nula = bez_nula.mean()
print(f"Aritmetička sredina bez nula: {mean_bez_nula:.2f}")

Aritmetička sredina bez nula: 3.33

In [ ]:
df1["Gate Location"].value_counts()

Gate Location
3    34409
4    29276
2    23371
1    21164
5    16779
0        1
Name: count, dtype: int64

In [ ]:
df1["Gate Location"].mean()

np.float64(2.977056)

In [ ]:
bez_nula = df1["Gate Location"][df1["Gate Location"] != 0]

mean_bez_nula = bez_nula.mean()
print(f"Aritmetička sredina bez nula: {mean_bez_nula:.2f}")

Aritmetička sredina bez nula: 2.98

In [16]:
df1["On-board Service"].mean()

np.float64(3.2780172921525668)

In [17]:
bez_nula = df1["On-board Service"][df1["On-board Service"] != 0]

mean_bez_nula = bez_nula.mean()
print(f"Aritmetička sredina bez nula: {mean_bez_nula:.2f}")

Aritmetička sredina bez nula: 3.28

In [18]:
df1["On-board Service"].value_counts()

On-board Service
4.0    11833
3.0     9135
5.0     9071
2.0     6644
1.0     5762
0.0        2
Name: count, dtype: int64

In [19]:
df1["Seat Comfort"].mean()

np.float64(3.3480575776851134)

In [20]:
bez_nula = df1["Seat Comfort"][df1["Seat Comfort"] != 0]

mean_bez_nula = bez_nula.mean()
print(f"Aritmetička sredina bez nula: {mean_bez_nula:.2f}")

Aritmetička sredina bez nula: 3.35

In [21]:
df1["Seat Comfort"].value_counts()

Seat Comfort
4.0    12276
5.0     9924
3.0     8304
2.0     6537
1.0     5405
0.0        1
Name: count, dtype: int64

In [22]:
df1["Leg Room Service"].mean()

np.float64(3.265295545032629)

In [24]:
bez_nula = df1["Leg Room Service"][df1["Leg Room Service"] != 0]

mean_bez_nula = bez_nula.mean()
print(f"Aritmetička sredina bez nula: {mean_bez_nula:.2f}")

Aritmetička sredina bez nula: 3.28

In [25]:
df1["Seat Comfort"].value_counts()

Seat Comfort
4.0    12276
5.0     9924
3.0     8304
2.0     6537
1.0     5405
0.0        1
Name: count, dtype: int64

In [26]:
kolone = ["Cleanliness", "Food and Drink", "In-flight Service",
          "In-flight Wifi Service", "In-flight Entertainment", "Baggage Handling"]

# Aritmetička sredina uključujući sve vrednosti
mean_all = df1[kolone].mean()
print("Srednja vrednost svih ocena:\n", mean_all)

# Aritmetička sredina bez nula
mean_bez_nula = df1[kolone].replace(0, pd.NA).mean()
print("\nSrednja vrednost bez nula:\n", mean_bez_nula)

Srednja vrednost svih ocena:
 Cleanliness                3.240158
Food and Drink             3.205645
In-flight Service          3.507763
In-flight Wifi Service     2.769407
In-flight Entertainment    3.351167
Baggage Handling           3.511862
dtype: float64

Srednja vrednost bez nula:
 Cleanliness                3.240616
Food and Drink             3.209349
In-flight Service          3.507928
In-flight Wifi Service     2.865818
In-flight Entertainment     3.35172
Baggage Handling           3.511862
dtype: object